name: Deploy for Beta Testing

on:
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Version Number in pubspec.yaml
        run: |
          perl -i -pe 's/^(version:\s+\d+\.\d+\.)(\d+)(\+)(\d+)$/$1.($2+1).$3.($4+1)/e' pubspec.yaml

      - name: Commit Version Number Update
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Update Version in pubspec.yaml"
          add: "pubspec.yaml"

  deploy-android:
    needs: update-version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Version Number in pubspec.yaml again as we perform a new checkout on the tag
        run: |
          perl -i -pe 's/^(version:\s+\d+\.\d+\.)(\d+)(\+)(\d+)$/$1.($2+1).$3.($4+1)/e' pubspec.yaml

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.6"
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"

      - name: Configure Keystore
        run: |
          echo '${{ secrets.PLAY_STORE_UPLOAD_KEY }}' | base64 --decode > android/keystore.jks
          echo '${{ secrets.KEY_PROPERTIES }}' > android/key.properties
          echo '${{ secrets.FCM_GOOGLE_SERVICES_JSON }}' > android/app/google-services.json

      - name: Build Appbundle
        run: |
          flutter pub get
          flutter build appbundle

      - name: Deploy to Google Play Store
        uses: r0adkll/upload-google-play@v1.0.19
        with:
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT }}
          packageName: com.tnexta.shortNewsMobile
          track: internal
          status: completed
